language: python

branches:
  only:
  - master
  - 0.0.2

python:
  - '3.8'
  - '3.7'
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install -r requirements_torch.txt
  - pip install -U pytest pytest-cov codecov pycodestyle flake8

script:
  - pytest tests/ --cov=./mvlearn/
  - pycodestyle mvlearn/
  - flake8 mvlearn
  - flake8 examples

after_success:
  - codecov
