language: python

branches:
  only:
  - master

python:
  - '3.8'
  - '3.7'
  - '3.6'

jobs:
  include:
    - stage: test_base
      install: pip install -r ./requirements/base.txt
      script: pytest tests/ --cov=./mvlearn/ --ignore=tests/multiviewica --ignore=tests/torch
    - stage: test_multiviewica
      install: pip install -r ./requirements/multiviewica.txt
      script: pytest tests/multiviewica/ --cov=./mvlearn/ --cov-append
    - stage: test_torch
      install: pip install -r ./requirements/torch.txt
      script: pytest tests/torch/ --cov=./mvlearn/ --cov-append
    - stage: codestyle
      install: pip install -U pytest pytest-cov codecov pycodestyle flake8
      script:
        pycodestyle mvlearn/
        flake8 mvlearn
        flake8 examples

after_success:
  - codecov
