name: circleci-redirector
on: [status]
jobs:
  unit-test:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python_version}}
      - name: Run Unit Tests
        run: |
          pip install -r ./requirements/base.txt
          pip install -U pytest pytest-cov codecov pycodestyle flake8
          pytest tests/ --cov=./mvlearn/ --ignore=tests/multiviewica --ignore=tests/torch --ignore=tests/graspy
          pip install -r ./requirements/multiviewica.txt
          pytest tests/multiviewica/ --cov=./mvlearn/ --cov-append
          pip install -r ./requirements/torch.txt
          pytest tests/torch/ --cov=./mvlearn/ --cov-append
          pip install -r ./requirements/graspy.txt
          pytest tests/graspy/ --cov=./mvlearn/ --cov-append
      - name: Check code formatting
        run: |
          pycodestyle mvlearn/
          flake8 mvlearn
          flake8 examples
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/dev/index.html
          circleci-jobs: build_docs
